config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :categories, only: [:new, :index, :show, :create,:edit ,:update, :destroy]do
    resources :diaries, only: [:new, :show, :create, :edit, :update, :destroy]
  end
  
  get "search" => "searches#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :diaries, dependent: :destroy
  
  validates :name, presence:true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :category
  
  has_one_attached :image
  
  validates :title, presence:true
  validates :body, presence:true
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end
  
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    @diaries = @category.diaries
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
    
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      render :edit
    end
  end
  
  def destroy
    category = Category.find(params[:id])
    category.destroy
    
    redirect_to categories_path
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @diary = Diary.new
  end
  
  def show
    @diary = Diary.find(params[:id])
    
  end
  
  def create
    @category = Category.find(params[:category_id])
    @diary = Diary.new(diary_params)
    @diary.category_id = @category.id
    if @diary.save
      redirect_to category_path(@diary.category)
    else
      render :new
    end
  end
  
  def edit
    @diary = Diary.find(params[:id])
  end
  
  def update
    @diary = Diary.find(params[:id])
    if @diary.update(diary_params)
      redirect_to category_diary_path(@diary.category, @diary)
    else
      render :edit
    end
  end
  
  def destroy
    diary = Diary.find(params[:id])
    diary.destroy
    
    redirect_to category_path(Category.find(params[:category_id]))
  end
  
  private
  
  def diary_params
    params.require(:diary).permit(:title, :body, :image)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    if params[:created_at] == ""
      @search_again = "日付を選択してください"
    else
      create_at = params[:created_at]
      @diaries = Diary.where(['created_at LIKE ? ', "#{create_at}%"])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Edit category</h2>
      <%= render 'layouts/error', obj: @category %>
      <%= form_with model: @category do |f| %>
        <h4>Name</h4>
        <%= f.text_field :name %>
        <%= f.submit 'Create' %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="container py-2 px-5 pb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2>Categories</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div>
      <% @categories.each do |category| %>
        <h4>
        ・<%= link_to category.name, category_path(category), class:"text-dark" %>
        </h4>
      <% end %>
      </div>
    </div>
    <div>
      <%= link_to "New category", new_category_path, class:"btn btn-dark" %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Category new</h2>
      <%= render 'layouts/error', obj: @category %>

      <%= form_with model: @category do |f| %>
        <h4>Name</h4>
        <%= f.text_field :name %>
  
        <%= f.submit 'Create' %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container py-1">
  <div class="row">
    <div class="col-3">
      <h1><%= @category.name %></h1>
    </div>  
    <div class="col-6">
      <div class="card-list-container py-5">
        <% @diaries.each do |diary| %>
          <div class="card w-75 mx-auto mt-4 shadow-lg">
            <%= link_to category_diary_path(diary.category, diary) do %>
              <%= image_tag diary.get_image(100,100), class:"card-img-top" %>
            <%end%>
            <div class="card-body">
              <div class="row">
                <div class="col-12">
                  <p class="card-title">
                    <%= link_to category_diary_path(@category, diary), class:"text-dark" do %>
                      <i class="fa fa-book"></i><%= diary.title %>
                    <%end%>
                  </p>
                  <p class="card-text">
                    <%= diary.body %>
                  </p>
                  <p class="text-right">
                    投稿：<%= diary.created_at.strftime('%Y/%m/%d') %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-3">
      <div>
        <%= link_to "New diary", new_category_diary_path(@category), class:"btn btn-dark" %>
      </div>
      <div><%= link_to 'Edit', edit_category_path(@category), class:"text-dark" %></div>
      <div><%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: '本当に消しますか？' }, class:"text-dark" %></div>
    </div>
  </div>
</div>

app/views/diaries/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Edit diary</h2>
      <%= render 'layouts/error', obj: @diary %>
      <%= form_with model:[@diary.category, @diary] do |f| %>
        <%= f.file_field :image, placeholder: "画像", accept: "image/*" %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Body</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Update' %>
      <% end %>
    </div>
  </div>
</div>

app/views/diaries/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Diary new</h2>
      <%= render 'layouts/error', obj: @diary %>
      <%= form_with model:[@category, @diary] do |f| %>
        <%= f.file_field :image, placeholder: "画像", accept: "image/*" %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Body</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create' %>
      <% end %>
    </div>
  </div>
</div>

app/views/diaries/show.html.erb
<div class="container py-1">
    <div class="row">
    <div class="col-6 offset-3">
      <h2><%= link_to @diary.category.name, category_path(@diary.category), class:"text-dark"%></h2>
      <div class="card-list-container py-1">
        <div class="card w-75 mx-auto mt-4 shadow-lg">
              <%= link_to category_diary_path(@diary.category, @diary) do %>
                <%= image_tag @diary.get_image(100,100), class:"card-img-top" %>
              <%end%>
              <div class="card-body">
                <div class="row">
                  <div class="col-12">
                    <p class="card-title">
                      <%= link_to @diary.title, category_diary_path(@diary.category, @diary), class:"text-dark"%>
                    </p>
                    <p class="card-text">
                      <%= @diary.body %>
                    </p>
                    <p class="text-right">
                    <%= link_to 'Edit', edit_category_diary_path(@diary.category, @diary), class:"text-dark" %>|<%= link_to 'Delete', category_diary_path(@diary.category, @diary), method: :delete, data: { confirm: '本当に消しますか？' }, class:"text-dark" %>
                    </p>
                    <p class="text-right">
                      投稿：<%= @diary.created_at.strftime('%Y/%m/%d') %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
      </div>
    </div>
    
  </div>
</div>

app/views/homes/top.html.erb
<h1>Hello!</h1>

<%= link_to "categories", categories_path, class:"text-dark" %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicApp2</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        
        <a class="navbar-brand" href="/"><span>Pic 日記</span></a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to categories_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Categories
              <% end %>
            </li>
            <li>
              <%= form_with url: search_path, method: :get, class: 'nav-link text-light' do |f| %>
                <%= f.date_field :created_at %>
                <%= f.submit '検索', class: 'btn btn-primary'  %>
              <% end %>
            </li>
          </ul>
        </div>
        
      </div>
    </nav>
    </header>
    
    <%= yield %>
    
    <footer>
      <div class='container mt-5'>
	      <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/searches/search.html.erb
<div class="container py-1">
  <div class="row">
    
    <div class="col-6 offset-3">
      <div class="card-list-container py-5">
        <% if @diaries.nil? %>
          <%= @search_again %>
        <% else %>
          <% @diaries.each do |diary| %>
            <div class="card w-75 mx-auto mt-4 shadow-lg">
              <%= link_to category_diary_path(diary.category, diary) do %>
                <%= image_tag diary.get_image(100,100), class:"card-img-top" %>
              <%end%>
              <div class="card-body">
                <div class="row">
                  <div class="col-12">
                    <p class="card-title">
                      <%= link_to diary.title, category_diary_path(diary.category, diary), class:"text-dark"%>
                    </p>
                    <p class="card-text">
                      <%= diary.body %>
                    </p>
                    <p class="text-right">
                      投稿：<%= diary.created_at.strftime('%Y/%m/%d') %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>  
      </div>
    </div>
    
  </div>
</div>